# Generated by Django 4.2.30 on 2026-08-22 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualTryOnGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outfit_id", models.CharField(blank=True, default="", max_length=100)),
                ("product_ids", models.JSONField(default=list)),
                ("user_prompt", models.TextField()),
                ("user_image_url", models.URLField(blank=True, default="")),
                ("result_image_url", models.URLField(blank=True, default="")),
                ("enhanced_prompt", models.TextField(blank=True, default="")),
                (
                    "model_used",
                    models.CharField(default="flux.2-klein-4b", max_length=100),
                ),
                (
                    "qwen_model_used",
                    models.CharField(default="qwen2.5-vl-7b-instruct", max_length=100),
                ),
                ("generation_time_ms", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("enhancing", "Enhancing Prompt"),
                            ("generating", "Generating Image"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryon_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
