# Generated by Django 4.2.30 on 2026-08-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_virtualtryongeneration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppearanceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(default="appearance_v1", max_length=20)),
                (
                    "quality_score",
                    models.FloatField(default=0.0, help_text="Image quality score 0-1"),
                ),
                (
                    "overall_confidence",
                    models.FloatField(
                        default=0.0, help_text="Overall analysis confidence 0-1"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance_analysis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appearance Analysis",
                "verbose_name_plural": "Appearance Analyses",
            },
        ),
        migrations.CreateModel(
            name="OutfitRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outfit_data",
                    models.JSONField(
                        default=dict,
                        help_text="Outfit details JSON compatible with SavedOutfit",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0, help_text="Overall outfit score 0-1"
                    ),
                ),
                (
                    "scores",
                    models.JSONField(
                        default=dict,
                        help_text={
                            "appropriateness": float,
                            "color_harmony": float,
                            "fit": float,
                            "style_match": float,
                        },
                    ),
                ),
                ("explanation", models.TextField(blank=True, default="")),
                (
                    "wardrobe_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether outfit uses user's digital wardrobe",
                    ),
                ),
                ("occasion", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appearance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outfit_recs",
                        to="api.appearanceanalysis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outfit_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="SkinAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tone", models.CharField(blank=True, default="", max_length=50)),
                ("undertone", models.CharField(blank=True, default="", max_length=50)),
                ("tone_confidence", models.FloatField(default=0.0)),
                ("undertone_confidence", models.FloatField(default=0.0)),
                ("L_median", models.FloatField(blank=True, null=True)),
                ("a_median", models.FloatField(blank=True, null=True)),
                ("b_median", models.FloatField(blank=True, null=True)),
                ("valid_pixel_count", models.IntegerField(blank=True, null=True)),
                ("std_dev", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appearance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skin",
                        to="api.appearanceanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skin Analysis",
            },
        ),
        migrations.CreateModel(
            name="ColorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "secondary_color",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "accent_color",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "contrast_level",
                    models.CharField(blank=True, default="medium", max_length=20),
                ),
                (
                    "seasonal_palette",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appearance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_profile",
                        to="api.appearanceanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Color Profile",
            },
        ),
        migrations.CreateModel(
            name="BodyProportions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("silhouette", models.CharField(blank=True, default="", max_length=50)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "shoulder_hip_ratio",
                    models.FloatField(
                        blank=True, help_text="Shoulder width / Hip width", null=True
                    ),
                ),
                (
                    "torso_leg_ratio",
                    models.FloatField(
                        blank=True, help_text="Torso length / Leg length", null=True
                    ),
                ),
                (
                    "upper_body_ratio",
                    models.FloatField(
                        blank=True, help_text="Upper body / Lower body", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appearance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_props",
                        to="api.appearanceanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Body Proportions",
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("like", "Liked"),
                            ("dislike", "Disliked"),
                            ("save", "Saved"),
                            ("purchase", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outfit_recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="api.outfitrecommendation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("user", "outfit_recommendation", "interaction_type")
                },
            },
        ),
    ]
